# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0002_auto_20171115_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttleroute',
            name='daily_pickup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Daily Pickup Date'),
        ),
    ]
