# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0003_shuttleroute_daily_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttleorder',
            name='daily_pickup_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
