# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0004_shuttleorder_daily_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttleorder',
            name='daily_pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
