# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0007_shuttleorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttleorder',
            name='evening_pickup_time',
            field=models.TimeField(blank=True, choices=[('05:00:00', '5:00'), ('05:30:00', '5:30'), ('06:00:00', '6:00'), ('06:30:00', '6:30'), ('07:00:00', '7:00'), ('07:30:00', '7:30'), ('08:00:00', '8:00'), ('08:30:00', '8:30')], null=True, verbose_name="User's Evening Pickup Time"),
        ),
        migrations.AlterField(
            model_name='shuttleorder',
            name='morning_pickup_time',
            field=models.TimeField(blank=True, choices=[('05:00:00', '5:00'), ('05:30:00', '5:30'), ('06:00:00', '6:00'), ('06:30:00', '6:30'), ('07:00:00', '7:00'), ('07:30:00', '7:30'), ('08:00:00', '8:00'), ('08:30:00', '8:30')], null=True, verbose_name="User's Morning Pickup Time"),
        ),
    ]
