# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0008_auto_20171206_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttleorder',
            name='evening_pickup_time',
            field=models.TimeField(blank=True, choices=[('17:00:00', '5:00PM'), ('17:30:00', '5:30PM'), ('18:00:00', '6:00PM'), ('18:30:00', '6:30PM'), ('19:00:00', '7:00PM'), ('07:30:00', '7:30'), ('20:00:00', '8:00PM'), ('20:30:00', '8:30PM')], null=True, verbose_name="User's Evening Pickup Time"),
        ),
        migrations.AlterField(
            model_name='shuttleorder',
            name='morning_pickup_time',
            field=models.TimeField(blank=True, choices=[('05:00:00', '5:00AM'), ('05:30:00', '5:30AM'), ('06:00:00', '6:00AM'), ('06:30:00', '6:30AM'), ('07:00:00', '7:00AM'), ('07:30:00', '7:30AM'), ('08:00:00', '8:00AM'), ('08:30:00', '8:30AM')], null=True, verbose_name="User's Morning Pickup Time"),
        ),
    ]
