# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0010_auto_20171207_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttleorder',
            name='reservation_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shuttleorder',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Not Started', 'Not Started'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=30),
        ),
    ]
