# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many_years_driving_professionally', models.IntegerField()),
                ('last_employer_name', models.CharField(max_length=255)),
                ('last_employer_address', models.CharField(max_length=255)),
                ('last_employer_number', models.CharField(max_length=11)),
                ('reason_for_leaving', models.CharField(max_length=255)),
                ('license_id', models.CharField(max_length=15)),
                ('license_exp_date', models.DateField()),
                ('medical_conditions', models.TextField(default='Nil')),
                ('referee1', models.CharField(max_length=255)),
                ('home_office_num1', models.CharField(max_length=11)),
                ('home_office_addr1', models.CharField(max_length=255)),
                ('referee2', models.CharField(blank=True, max_length=255, null=True)),
                ('home_office_num2', models.CharField(blank=True, max_length=11, null=True)),
                ('home_office_addr2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Driver_CVs',
                'verbose_name': 'Driver_CV',
            },
        ),
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('mid_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('home_address', models.CharField(max_length=255)),
                ('phone_num1', models.CharField(max_length=11)),
                ('phone_num2', models.CharField(blank=True, max_length=11, null=True)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=7)),
                ('available_for_use', models.BooleanField()),
                ('isAvailable', models.BooleanField()),
                ('nextAvailability', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'DriverInfos',
                'verbose_name': 'DriverInfo',
            },
        ),
        migrations.CreateModel(
            name='DriverOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_within_lagos', models.BooleanField()),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Not Started', 'Not Started')], max_length=30)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=7)),
            ],
            options={
                'verbose_name_plural': 'DriverOrders',
                'verbose_name': 'DriverOrder',
            },
        ),
    ]
