# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='category',
            field=models.CharField(choices=[('Class A', 'A'), ('Class B', 'B'), ('Class C', 'C')], max_length=7),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='phone_num1',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='phone_num2',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
