# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20171207_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorder',
            name='pickup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
