# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Space Bus', 'Space Bus'), ('SUV', 'SUV'), ('Saloon Car', 'Saloon Car'), ('Coaster Bus', 'Coaster Bus'), ('Mini Bus', 'Mini Bus')], max_length=15)),
                ('make', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('license_plate', models.CharField(max_length=15)),
                ('luxury', models.BooleanField()),
                ('available_for_use', models.BooleanField()),
                ('isAvailable', models.BooleanField()),
                ('nextAvailability', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'CarInfos',
                'verbose_name': 'CarInfo',
            },
        ),
        migrations.CreateModel(
            name='CarOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_within_lagos', models.BooleanField()),
                ('pickup_address', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=7)),
                ('pickup_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Not Started', 'Not Started')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'CarOrders',
                'verbose_name': 'CarOrder',
            },
        ),
    ]
